select * from customer limit 20;

--What is the total revenue generated by male vs. female customers
select gender, sum(purchase_amount) as revenue 
from customer 
group by gender;

--Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and 
purchase_amount>= (select avg(purchase_amount) from customer)
;
--Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "avg prd rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
avg(purchase_amount)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--and advanced option for same question
SELECT 
    subscription_status,
    COUNT(customer_id) as total_customers,
    ROUND(AVG(purchase_amount), 2) as avg_spend,
    MAX(purchase_amount) as highest_individual_purchase,
    MIN(purchase_amount) as lowest_individual_purchase,
    ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status;

--using case when :
SELECT 
    subscription_status,
    CASE 
        WHEN previous_purchases > 10 THEN 'Loyal/Heavy Buyer'
        WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Frequent Buyer'
        ELSE 'Occasional/New Buyer'
    END as loyalty_tier,
    COUNT(customer_id) as total_customers,
    ROUND(AVG(purchase_amount), 2) as avg_individual_ticket_size,
    ROUND(SUM(purchase_amount), 2) as total_revenue_contribution
FROM customer
GROUP BY subscription_status, 
         CASE 
             WHEN previous_purchases > 10 THEN 'Loyal/Heavy Buyer'
             WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Frequent Buyer'
             ELSE 'Occasional/New Buyer'
         END
ORDER BY subscription_status, total_revenue_contribution DESC;

--Find the Top Individual Spenders
SELECT 
    customer_id, 
    subscription_status, 
    purchase_amount
FROM customer
ORDER BY purchase_amount DESC
LIMIT 10;


--Find the most spending customers
WITH top_spenders AS (
    SELECT 
        customer_id,
        subscription_status,
        purchase_amount,
        DENSE_RANK() OVER (ORDER BY purchase_amount DESC) as spend_rank
    FROM customer
    LIMIT 50 -- Isolate the top 50 highest individual transactions
)
SELECT 
    subscription_status,
    COUNT(customer_id) as number_of_elite_customers,
    ROUND(COUNT(customer_id) * 100.0 / (SELECT COUNT(*) FROM top_spenders), 2) as percentage_share,
    ROUND(AVG(purchase_amount), 2) as average_elite_spend
FROM top_spenders
GROUP BY subscription_status;

--Find highest spenders wiith min and max amount as well
WITH ranked_customers AS (
    SELECT 
        subscription_status,
        purchase_amount,
        NTILE(10) OVER (PARTITION BY subscription_status ORDER BY purchase_amount DESC) as spend_decile
    FROM customer
)
SELECT 
    subscription_status,
    MAX(purchase_amount) as max_spend,
    MIN(purchase_amount) as min_spend,
    ROUND(AVG(purchase_amount), 2) as top_decile_average_spend
FROM ranked_customers
WHERE spend_decile = 1 -- Isolate ONLY the top 10% highest spenders of each group
GROUP BY subscription_status;

--Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases =1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "no of cust"
from customer_type
group by customer_segment;


--What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;


--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

--What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;